--Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
----------------------------------------------------------------------------------
--Tool Version: Vivado v.2019.2 (win64) Build 2708876 Wed Nov  6 21:40:23 MST 2019
--Date        : Tue Nov 15 20:46:19 2022
--Host        : DESKTOP-0DAFOBK running 64-bit major release  (build 9200)
--Command     : generate_target SRAM_CTRL.bd
--Design      : SRAM_CTRL
--Purpose     : IP block netlist
----------------------------------------------------------------------------------
